#!/bin/bash

classpath=bin:org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.7:lib/colt.jar:lib/commons-email-1.3.1.jar

if [ $# -lt 5 ]; then
	echo Must be executed in the workspace/Skyline for classpath to be correct
	echo USAGE: CMD testname algorithm dataset n d
	exit 1
fi

testname=$1
algorithm=$2
dataset=$3
n=$4
d=$5

for threadcount in 1 2 4 6 12 24 32 64 128 256 512 1024
do
	echo "Testing $2 with $threadcount threads"
	runid=`printf "%04d" $threadcount`
	mkdir -p ../../results/experiment2/$testname
	java -cp $classpath no.ntnu.skyline.Experiment2 $algorithm $threadcount $dataset $n $d >\
	 ../../results/experiment2/$testname/${algorithm}_${dataset}_N${n}_D${d}_${runid}
done
